server:
  port: 8090
spring:
  application:
    name: gitConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/egBean/springcloud.git
          search-paths: gitconfig
          username: egbean
          password: wfw12345
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



